# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-2019

variables:
  buildConfig: 'Release'

# task: DotNetCoreCLI@2
#   displayName: 'Build the project'
#   inputs:
#     command: 'build'
#     arguments: '--no-restore --configuration Release'
#     projects: '**/*.csproj'

# task: testdeploy@1
#   inputs:
#     azureSubscription: 'Pay-As-You-Go'
#     appType: 'webApp'
#     appName: 'myWebAppName'
#     deployToSlotOrASE: true
#     resourceGroupName: 'myResourceGroup'
#     slotName: 'staging'
#     deploymentMethod: 'auto'
steps:
- script: echo Hello, world! $(buildConfig) and path $(Build.SourcesDirectory) 
    echo "Structure of work folder of this pipeline:"
    tree $(Agent.WorkFolder)\1 /f
    echo "Build.ArtifactStagingDirectory:" 
    echo "$(Build.ArtifactStagingDirectory)"
    echo "Build.BinariesDirectory:" 
    echo "$(Build.BinariesDirectory)"
    echo "Build.SourcesDirectory:"
    echo "$(Build.SourcesDirectory)"
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    dotnet build --configuration $(buildConfig)
  displayName: 'Run a multi-line script and build'
